### ISSUE TITLE
when I use it

### ISSUE THREAD

**Issue by daoSs** [blockhead123/image-gallery-threejs#2]
I found ‘Uncaught SecurityError’ in my F12

**Comment by blockhead123** [comment]
Hi @daoSs what browser were you using when you had that security error?

**Comment by daoSs** [comment]
chome&firefox&ie ......  all browsers

**Comment by daoSs** [comment]
"89three.min.js:507 Uncaught SecurityError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at http://www.jqcool.net/demo/201504/image-gallery-threejs/images/image3.jpg may not be loaded."

**Comment by daoSs** [comment]
I found the problem.But now，I have a new problem:How do I change the shape of the image?They are square by default.

**Comment by blockhead123** [comment]
Hi @daoSs yah thats a security error, good thing you found it already :) . For the shape of the image as of now it's not available yet and you have to handle the image adjustment over at php gdLib or have all images cropped at the same aspect ratio. I will be resolving this soon when i'm not that busy anymore.

**Comment by blockhead123** [comment]
Hi @daoSs I removed the panelSize parameter and introduced two new parameters which are panelSizeW and panelSizeH. so right now you can change the shape of the image already. Hope that helps :)
